In [1]:
!pip install jieba
import jieba

text = "我爱自然语言处理，它是一门很有趣的学科。"
# 1. 精确模式 (默认模式)：试图将句子最精确地切开
seg_list_precise = jieba.cut(text, cut_all=False)
print(f"精确模式: {' / '.join(seg_list_precise)}")

# 2. 全模式：把句子中所有可以成词的词语都扫描出来
seg_list_all = jieba.cut(text, cut_all=True)
print(f"全模式: {' / '.join(seg_list_all)}")

# 3. 搜索引擎模式：在精确模式的基础上，对长词再次切分
seg_list_search = jieba.cut_for_search(text)
print(f"搜索引擎模式: {' / '.join(seg_list_search)}")

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ASUS\AppData\Local\Temp\jieba.cache
Loading model cost 0.898 seconds.
Prefix dict has been built successfully.


精确模式: 我 / 爱 / 自然语言 / 处理 / ， / 它 / 是 / 一门 / 很 / 有趣 / 的 / 学科 / 。
全模式: 我 / 爱 / 自然 / 自然语言 / 语言 / 处理 / ， / 它 / 是 / 一门 / 很 / 有趣 / 的 / 学科 / 。
搜索引擎模式: 我 / 爱 / 自然 / 语言 / 自然语言 / 处理 / ， / 它 / 是 / 一门 / 很 / 有趣 / 的 / 学科 / 。


In [2]:
import jieba.posseg as pseg

text = "我爱自然语言处理，它是一门很有趣的学科。"

# 运行词性标注
pos_tags = pseg.cut(text)

print("词性标注结果:")
for word, flag in pos_tags:
    print(f"{word} ({flag})")

词性标注结果:
我 (r)
爱 (v)
自然语言 (l)
处理 (v)
， (x)
它 (r)
是 (v)
一门 (m)
很 (zg)
有趣 (a)
的 (uj)
学科 (n)
。 (x)


In [3]:
# 1. 准备一份停用词表
# (在真实项目中，会从一个大文件加载，比如 哈工大停用词表。这里我们手动定义一个小的)
stopwords = {"的", "是", "在", "我", "它", "，", "。"}

# 2. 准备原始句子
text = "我爱自然语言处理，它是一门很有趣的学科。"

# 3. 先进行分词
seg_list = jieba.cut(text, cut_all=False)

# 4. 过滤停用词 (使用列表推导式)
filtered_words = [word for word in seg_list if word.strip() and word not in stopwords]

print(f"原始分词: {' / '.join(jieba.cut(text, cut_all=False))}")
print(f"去除停用词后: {' / '.join(filtered_words)}")

原始分词: 我 / 爱 / 自然语言 / 处理 / ， / 它 / 是 / 一门 / 很 / 有趣 / 的 / 学科 / 。
去除停用词后: 爱 / 自然语言 / 处理 / 一门 / 很 / 有趣 / 学科


In [4]:
import jieba
def load_stopwords(filepath):
    """
    从指定路径加载停用词表。
    Args:
        filepath (str): 停用词文件的路径
    Returns:
        set: 包含所有停用词的集合 (set)
    """
    print(f"正在从 {filepath} 加载停用词...")
    stopwords = set()
    
    # 1. 打开文件
    #    'r' 表示读取模式
    #    encoding='utf-8' 是处理中文文件的标准做法，防止乱码
    with open(filepath, 'r', encoding='utf-8') as f:
        # 2. 逐行读取
        for line in f:
            # 3. 清理每行：
            #    .strip() 会移除开头和结尾的空白字符（比如换行符 \n 和空格）
            word = line.strip()
            # 4. 确保行不是空的
            if word:
                stopwords.add(word)
    
    print(f"成功加载 {len(stopwords)} 个停用词。")
    return stopwords

# 1. 准备停用词表 (从文件加载)
#    (hit_stopwords.txt
stopwords_filepath = 'hit_stopwords.txt'
stopwords = load_stopwords(stopwords_filepath)

# 打印几个看看
print(f"加载的停用词示例: {list(stopwords)[:5]}")


# 2. 准备原始句子
text = "我爱自然语言处理，它是一门很有趣的学科。"

# 3. 先进行分词
seg_list = jieba.cut(text, cut_all=False)

# 4. 过滤停用词 (这里的逻辑和之前一样)
filtered_words = [word for word in seg_list if word.strip() and word not in stopwords]

print(f"\n原始分词: {' / '.join(jieba.cut(text, cut_all=False))}")
print(f"去除停用词后: {' / '.join(filtered_words)}")

正在从 hit_stopwords.txt 加载停用词...
成功加载 749 个停用词。
加载的停用词示例: ['#', '开始', '［②ｊ］', '②ｃ', '矣']

原始分词: 我 / 爱 / 自然语言 / 处理 / ， / 它 / 是 / 一门 / 很 / 有趣 / 的 / 学科 / 。
去除停用词后: 爱 / 自然语言 / 处理 / 一门 / 很 / 有趣 / 学科


In [5]:
# 准备语料 和 分词
!pip install jieba
import jieba

# 1. 原始中文语料
corpus_raw = [
    "我喜欢学习自然语言处理",
    "我讨厌学习线性代数",
    "自然语言处理很有趣，线性代数也很有趣"
]

# 2. 创建一个函数，用于分词并用空格连接
stopwords = {"也", "很", "的", "，"} # 假设一个小的停用词表
def chinese_tokenizer(text):
    words = jieba.cut(text)
    return " ".join([word for word in words if word.strip() and word not in stopwords])
# 3. 处理我们的语料库
corpus_tokenized = [chinese_tokenizer(text) for text in corpus_raw]
print("分词后的语料库:")
for doc in corpus_tokenized:
    print(f"  - {doc}")

分词后的语料库:
  - 我 喜欢 学习 自然语言 处理
  - 我 讨厌 学习 线性代数
  - 自然语言 处理 有趣 线性代数 有趣


In [9]:
# 使用 CountVectorizer 实现 TF
from sklearn.feature_extraction.text import CountVectorizer
# 1. 初始化 CountVectorizer
# 它可以看作是"词袋模型"的TF实现
tf_vectorizer = CountVectorizer()
# 2. 拟合和转换我们分好词的语料库
# fit: 学习词典 
# transform: 把句子转换成向量
X_tf = tf_vectorizer.fit_transform(corpus_tokenized)

# 3. 查看结果
print("\n--- TF (CountVectorizer) 结果 ---")
print("词典 (Vocabulary):")
# .get_feature_names_out() 是新版 sklearn 的标准用法
print(tf_vectorizer.get_feature_names_out())

print("\n词频 (TF) 矩阵 (稀疏矩阵表示):")
print(X_tf)

print("\n词频 (TF) 矩阵 (密集数组表示):")
print(X_tf.toarray())



--- TF (CountVectorizer) 结果 ---
词典 (Vocabulary):
['喜欢' '处理' '学习' '有趣' '线性代数' '自然语言' '讨厌']

词频 (TF) 矩阵 (稀疏矩阵表示):
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (3, 7)>
  Coords	Values
  (0, 0)	1
  (0, 2)	1
  (0, 5)	1
  (0, 1)	1
  (1, 2)	1
  (1, 6)	1
  (1, 4)	1
  (2, 5)	1
  (2, 1)	1
  (2, 4)	1
  (2, 3)	2

词频 (TF) 矩阵 (密集数组表示):
[[1 1 1 0 0 1 0]
 [0 0 1 0 1 0 1]
 [0 1 0 2 1 1 0]]


In [13]:
!pip install jieba
import jieba

# 1. 原始中文语料
corpus_raw = [
    "我喜欢学习自然语言处理",
    "我讨厌学习线性代数",
    "自然语言处理很有趣，线性代数也很有趣"
]

# 2. 创建一个函数，用于分词并用空格连接
stopwords = {"也", "很", "的", "，"} # 假设一个小的停用词表
def chinese_tokenizer(text):
    words = jieba.cut(text)
    return " ".join([word for word in words if word.strip() and word not in stopwords])
# 3. 处理我们的语料库
corpus_tokenized = [chinese_tokenizer(text) for text in corpus_raw]
print("分词后的语料库:")
for doc in corpus_tokenized:
    print(f"  - {doc}")

    
#  使用 TfidfVectorizer 实现 TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. 初始化 TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

# 2. 拟合(fit)和转换(transform)
X_tfidf = tfidf_vectorizer.fit_transform(corpus_tokenized)

# 3. 查看结果
print("\n--- TF-IDF (TfidfVectorizer) 结果 ---")
print("词典 (Vocabulary):")
print(tfidf_vectorizer.get_feature_names_out())

print("\nTF-IDF 权重矩阵 (密集数组表示):")
print(X_tfidf.toarray())

print("\nTF-IDF 权重矩阵 (稀疏矩阵表示):")
print(X_tfidf)

分词后的语料库:
  - 我 喜欢 学习 自然语言 处理
  - 我 讨厌 学习 线性代数
  - 自然语言 处理 有趣 线性代数 有趣

--- TF-IDF (TfidfVectorizer) 结果 ---
词典 (Vocabulary):
['喜欢' '处理' '学习' '有趣' '线性代数' '自然语言' '讨厌']

TF-IDF 权重矩阵 (密集数组表示):
[[0.60465213 0.45985353 0.45985353 0.         0.         0.45985353
  0.        ]
 [0.         0.         0.51785612 0.         0.51785612 0.
  0.68091856]
 [0.         0.31757018 0.         0.83513325 0.31757018 0.31757018
  0.        ]]

TF-IDF 权重矩阵 (稀疏矩阵表示):
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11 stored elements and shape (3, 7)>
  Coords	Values
  (0, 0)	0.6046521283053111
  (0, 2)	0.4598535287588349
  (0, 5)	0.4598535287588349
  (0, 1)	0.4598535287588349
  (1, 2)	0.5178561161676974
  (1, 6)	0.680918560398684
  (1, 4)	0.5178561161676974
  (2, 5)	0.3175701804283441
  (2, 1)	0.3175701804283441
  (2, 4)	0.3175701804283441
  (2, 3)	0.8351332477563848
