## 反馈

接下来一周争取能够学会使用sklearn库实现onehot编码和tfidf计算，如果有时间在算一下文本之间的相似度。加油！

In [1]:
import numpy as np

# 输入数据：类别标签列表
labels = [0, 2, 1, 3, 1, 0]

# 计算类别总数
num_classes = max(labels) + 1  # 4

# 初始化全零矩阵
one_hot_matrix = np.zeros((len(labels), num_classes))

# 填充one-hot编码
for i, label in enumerate(labels):
    one_hot_matrix[i, label] = 1

print(one_hot_matrix)

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [3]:
import numpy as np

# 输入数据：文本句子列表
sentences = [
    "我 毕业 于 温州第二高级中学",
    "现 就读 于 浙江工业大学"
]

# 步骤1: 构建词汇表
token_index = {}
for sentence in sentences:
    for word in sentence.split():
        if word not in token_index:
            token_index[word] = len(token_index)  # 索引从0开始

# 步骤2: 创建编码矩阵
results = np.zeros((len(sentences), len(token_index)))

# 步骤3: 填充编码矩阵
for i, sentence in enumerate(sentences):
    for word in sentence.split():
        j = token_index[word]
        results[i, j] = 1

print("词汇表:", token_index)
print("编码矩阵:\n", results)

词汇表: {'我': 0, '毕业': 1, '于': 2, '温州第二高级中学': 3, '现': 4, '就读': 5, '浙江工业大学': 6}
编码矩阵:
 [[1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1. 1. 1.]]
